# Generated by Django 5.0.4 on 2024-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='father_name',
            field=models.TextField(default='Rahima'),
        ),
        migrations.AlterField(
            model_name='modelform',
            name='roll',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
