# Generated by Django 5.0.4 on 2024-05-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_modelform_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform',
            name='date_field',
            field=models.DateField(default='2024-05-24'),
        ),
        migrations.AddField(
            model_name='modelform',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default='5.67', max_digits=5),
        ),
        migrations.AddField(
            model_name='modelform',
            name='email_field',
            field=models.EmailField(default='exmple@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='modelform',
            name='float_field',
            field=models.FloatField(default='4.56'),
        ),
        migrations.AddField(
            model_name='modelform',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default='192.0.2.1'),
        ),
    ]
