# Generated by Django 5.0.4 on 2024-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_modelform_date_field_modelform_decimal_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform',
            name='text_field',
            field=models.TextField(default='asdfdf fdsf'),
        ),
    ]
