# Generated by Django 5.0.4 on 2024-05-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
    ]
